### PR TITLE
test sub commands

### PR DESCRIPTION
**Pull request by Krishnag09**
- fixed existing tests. 
- made recommended changes
- added sub-command filter test.

### CODE REVIEW

**Comment by Krishnag09** [comment]
@LuisanaMTDev - for some reason, i am not able to import the`export_tasks` from `info_commands`, can you please have a look?

**Comment by LuisanaMTDev** [comment]
I think it is cuz you're importing the commands wrong in test_sub_commands.py, you're not pointing to the module that contains the function.

The imports should be like this ```
python

from daily_tasks.commands.info_commands import export_tasks
```

**Comment by Krishnag09** [comment]
it should work, as `from daily_tasks.commands import filter_tasks
` works. the __init__ should take care of it. Could you try and run the tests at your end and check once the issue you see?

**Comment by LuisanaMTDev** [comment]
I don't have my PC yet

**Comment by LuisanaMTDev** [comment]
A question, do you get ModuleNotFoundError when you execute test_sub_commands.py file?

**Comment by LuisanaMTDev** [comment]
You were right with the imports, they work, so I run the test_sub_commands.py file and I get ModuleNotFoundError error, I solved it installing the package (I install it in editable mode), you can install it with `pip install -e  .` command.

I will fix a few errors that I found and then do a PR.

**Comment by LuisanaMTDev** [comment]
@Krishnag09 You were right with the imports, they work, so I run the test_sub_commands.py file and I get ModuleNotFoundError error, I solved it installing the package (I install it in editable mode), you can install it with `pip install -e  .` command.

I will fix a few errors that I found and then do a PR.

**Comment by LuisanaMTDev** [comment]
My commit was link to this PR (I didn't know that was happened 😅).

**Comment by Krishnag09** [comment]
> My commit was link to this PR (I didn't know that was happened 😅).

thats ok, so now i just need to install the package and it should run?

**Comment by LuisanaMTDev** [comment]
> > My commit was link to this PR (I didn't know that was happened 😅).
> 
> thats ok, so now i just need to install the package and it should run?

Yes, let me know if there's any problem.

**Comment by LuisanaMTDev** [comment]
@Krishnag09 Let me know when this PR is done.

**Comment by Krishnag09** [comment]
@LuisanaMTDev - done now

**Review by LuisanaMTDev — APPROVED** [review]

**Pull request merged**
